/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Widya
 */
public class menu extends javax.swing.JFrame {

    public menu() {
        initComponents();
        
        setTanggal();
        jam();
    }
    
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        tglTF.setText(kal.format(skrg));
    }
    
    public void jam() {
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MMM-yyyy");
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                String Jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jamTF.setText("  " + Jam + " : " + menit + " : " + detik + "  ");
                
            }
        };
        new javax.swing.Timer(1000, taskPerformer).start();
    }
    
    public void hakAksesPemilik(){
        
    }
    
    public void hakAksesKasir(){
        barangBT.setEnabled(false);
        xMaster.setEnabled(false);
        xTransaksi.setEnabled(false);
        xPengguna.setEnabled(false);
        xLapBeli.setEnabled(false);
        xLapBarang.setEnabled(false);
        pembelianBT.setEnabled(false);
        supplierBT.setEnabled(false);
         homeBT.setEnabled(false);
    }
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        supplierBT = new javax.swing.JButton();
        pembelianBT = new javax.swing.JButton();
        penjualanBT = new javax.swing.JButton();
        homeBT = new javax.swing.JButton();
        barangBT = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jam = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jamTF = new javax.swing.JLabel();
        tglTF = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dp = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        xLogout = new javax.swing.JMenuItem();
        xMaster = new javax.swing.JMenu();
        xBarang = new javax.swing.JMenuItem();
        xSupplier = new javax.swing.JMenuItem();
        xTransaksi = new javax.swing.JMenu();
        xBeli = new javax.swing.JMenuItem();
        xJual = new javax.swing.JMenuItem();
        xLaporan = new javax.swing.JMenu();
        xLapBarang = new javax.swing.JMenuItem();
        xLapBeli = new javax.swing.JMenuItem();
        xLapJual = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        xPengguna = new javax.swing.JMenuItem();
        xEditPass = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 750));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo1.JPG"))); // NOI18N

        supplierBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supplierBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Suplier.png"))); // NOI18N
        supplierBT.setText("DATA SUPPLIER");
        supplierBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBTActionPerformed(evt);
            }
        });

        pembelianBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pembelianBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pembelian.png"))); // NOI18N
        pembelianBT.setText("PEMBELIAN BARANG");
        pembelianBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianBTActionPerformed(evt);
            }
        });

        penjualanBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        penjualanBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Penjualan.gif"))); // NOI18N
        penjualanBT.setText("PENJUALAN BARANG");
        penjualanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanBTActionPerformed(evt);
            }
        });

        homeBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home-icon.png"))); // NOI18N
        homeBT.setText("HOME");
        homeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTActionPerformed(evt);
            }
        });

        barangBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        barangBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/barang1.png"))); // NOI18N
        barangBT.setText("DATA BARANG");
        barangBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(653, 653, 653))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(homeBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(barangBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(supplierBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pembelianBT, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(penjualanBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addComponent(jSeparator11)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(homeBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barangBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierBT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pembelianBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penjualanBT)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 750));

        jam.setBackground(new java.awt.Color(204, 204, 255));
        jam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jam.setPreferredSize(new java.awt.Dimension(1500, 130));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("APLIKASI PENJUALAN PIGURA");

        jamTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jamTF.setText("JAM");

        tglTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tglTF.setText("TANGGAL");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jamLayout = new javax.swing.GroupLayout(jam);
        jam.setLayout(jamLayout);
        jamLayout.setHorizontalGroup(
            jamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jamLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel7))
                    .addGroup(jamLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addGroup(jamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jamTF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tglTF, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(102, 102, 102))
        );
        jamLayout.setVerticalGroup(
            jamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jamLayout.createSequentialGroup()
                .addGroup(jamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jamLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jamLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jamLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jamTF, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tglTF)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1090, 130));

        dp.setBackground(new java.awt.Color(204, 204, 255));
        dp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon Toko Online - 1.jpg"))); // NOI18N

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        dp.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 1080, 620));

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        xLogout.setText("Exit");
        xLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(xLogout);

        jMenuBar1.add(jMenu1);

        xMaster.setText("master");

        xBarang.setText("barang");
        xBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xBarangActionPerformed(evt);
            }
        });
        xMaster.add(xBarang);

        xSupplier.setText("supplier");
        xSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xSupplierActionPerformed(evt);
            }
        });
        xMaster.add(xSupplier);

        jMenuBar1.add(xMaster);

        xTransaksi.setText("transaksi");

        xBeli.setText("Pembeliaan");
        xBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xBeliActionPerformed(evt);
            }
        });
        xTransaksi.add(xBeli);

        xJual.setText("Penjualan");
        xJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xJualActionPerformed(evt);
            }
        });
        xTransaksi.add(xJual);

        jMenuBar1.add(xTransaksi);

        xLaporan.setText("laporan");

        xLapBarang.setText("barang");
        xLapBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xLapBarangActionPerformed(evt);
            }
        });
        xLaporan.add(xLapBarang);

        xLapBeli.setText("pembelian");
        xLapBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xLapBeliActionPerformed(evt);
            }
        });
        xLaporan.add(xLapBeli);

        xLapJual.setText("penjualan");
        xLapJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xLapJualActionPerformed(evt);
            }
        });
        xLaporan.add(xLapJual);

        jMenuBar1.add(xLaporan);

        jMenu5.setText("Utility");

        xPengguna.setText("datapengguna");
        xPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPenggunaActionPerformed(evt);
            }
        });
        jMenu5.add(xPengguna);

        xEditPass.setText("gantipassword");
        xEditPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xEditPassActionPerformed(evt);
            }
        });
        jMenu5.add(xEditPass);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barangBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangBTActionPerformed
        barang b= new barang();
        dp.add(b);
        adm a = new adm();
        dp.remove(a);
        b.setVisible(true);
    }//GEN-LAST:event_barangBTActionPerformed

    private void supplierBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBTActionPerformed
        supplier sp= new supplier();
        dp.add(sp);
        adm a = new adm();
        dp.remove(a);
        sp.setVisible(true);
    }//GEN-LAST:event_supplierBTActionPerformed

    private void pembelianBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianBTActionPerformed
        bbarang bb= new bbarang();
        dp.add(bb);
        adm a = new adm();
        dp.remove(a);
        bb.setVisible(true);
    }//GEN-LAST:event_pembelianBTActionPerformed

    private void penjualanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanBTActionPerformed
        new FormTransaksi().setVisible(true);
//        jual j= new jual();
//        dp.add(j);
//        adm a = new adm();
//        dp.remove(a);
//        j.setVisible(true);
    }//GEN-LAST:event_penjualanBTActionPerformed

    private void xBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xBarangActionPerformed
        barang b= new barang();
        dp.add(b);
        adm a = new adm();
        dp.remove(a);
        b.setVisible(true);
    }//GEN-LAST:event_xBarangActionPerformed

    private void xBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xBeliActionPerformed
        bbarang bb= new bbarang();
        dp.add(bb);
        adm a = new adm();
        dp.remove(a);
        bb.setVisible(true);
    }//GEN-LAST:event_xBeliActionPerformed

    private void xJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xJualActionPerformed
        new FormTransaksi().setVisible(true);
//        jual j= new jual();
//        dp.add(j);
//        adm a = new adm();
//        dp.remove(a);
//        j.setVisible(true);
    }//GEN-LAST:event_xJualActionPerformed

    private void xLapBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xLapBeliActionPerformed
        laporanpembelian lp=new laporanpembelian();
        lp.setLocationRelativeTo(null);
        lp.setVisible(true);
    }//GEN-LAST:event_xLapBeliActionPerformed

    private void xLapJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xLapJualActionPerformed
        laporanpenjualan lp=new laporanpenjualan();
        lp.setLocationRelativeTo(null);
        lp.setVisible(true);
    }//GEN-LAST:event_xLapJualActionPerformed

    private void xLapBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xLapBarangActionPerformed
        laporanbarang lb=new laporanbarang();
        lb.setLocationRelativeTo(null);
        lb.setVisible(true);
    }//GEN-LAST:event_xLapBarangActionPerformed

    private void xPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPenggunaActionPerformed
        daftar d=new daftar();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_xPenggunaActionPerformed

    private void xSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xSupplierActionPerformed
        supplier sp= new supplier();
        dp.add(sp);
        adm a = new adm();
        dp.remove(a);
        sp.setVisible(true);
    }//GEN-LAST:event_xSupplierActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void homeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTActionPerformed
        menu a = new menu();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeBTActionPerformed

    private void xEditPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xEditPassActionPerformed
        gantipassword h=new gantipassword();
        h.setLocationRelativeTo(null);
        h.setVisible(true);   
    }//GEN-LAST:event_xEditPassActionPerformed

    private void xLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xLogoutActionPerformed
        login h=new login();
        h.setLocationRelativeTo(null);
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_xLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barangBT;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JButton homeBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel jam;
    private javax.swing.JLabel jamTF;
    private javax.swing.JButton pembelianBT;
    private javax.swing.JButton penjualanBT;
    private javax.swing.JButton supplierBT;
    private javax.swing.JLabel tglTF;
    private javax.swing.JMenuItem xBarang;
    private javax.swing.JMenuItem xBeli;
    private javax.swing.JMenuItem xEditPass;
    private javax.swing.JMenuItem xJual;
    private javax.swing.JMenuItem xLapBarang;
    private javax.swing.JMenuItem xLapBeli;
    private javax.swing.JMenuItem xLapJual;
    private javax.swing.JMenu xLaporan;
    private javax.swing.JMenuItem xLogout;
    private javax.swing.JMenu xMaster;
    private javax.swing.JMenuItem xPengguna;
    private javax.swing.JMenuItem xSupplier;
    private javax.swing.JMenu xTransaksi;
    // End of variables declaration//GEN-END:variables

}
